---
- import_playbook: plays/00-system.yml
- import_playbook: plays/01-security.yml
- import_playbook: plays/02-dev-tools.yml
- import_playbook: plays/03-desktop.yml
- import_playbook: plays/04-dotfiles.yml
- import_playbook: plays/05-gaming.yml
